name: Build with Typst

on: [push, workflow_dispatch]
permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: working
      - run: |
          # install typst
          curl -OL https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz
          tar xf typst-x86_64-unknown-linux-musl.tar.xz
          sudo mv typst-x86_64-unknown-linux-musl/typst /bin/typst

          # fonts
          mkdir -p fonts/
          for wght in $(seq 200 100 900); do
            curl -L "https://cdn.jsdelivr.net/fontsource/fonts/source-sans-3@latest/latin-$wght-normal.ttf" -o "fonts/SourceSans3-$wght.ttf"
            curl -L "https://cdn.jsdelivr.net/fontsource/fonts/source-sans-3@latest/latin-$wght-italic.ttf" -o "fonts/SourceSans3-$wght-italic.ttf"
          done

          # compile
          mkdir -p working/pdf/
          typst c working/resume.typ working/pdf/resume.pdf --font-path fonts/
          typst c working/resume-long.typ working/pdf/resume-long.pdf --font-path fonts/

          # commit
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          cd working
          git add pdf
          git commit -m "chore: update PDFs"
          git push
